name: Next.js Full Release Deploy to E:\react

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted
    env:
      ACTIONS_STEP_DEBUG: true
      CI: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci 2>&1

      - name: Build project (verbose)
        shell: cmd
        run: |
          echo Starting build...
          npm run build 2>&1
          if errorlevel 1 (
            echo ::error::Build failed with exit code %errorlevel%
            exit /b %errorlevel%
          )

      - name: Copy full projects
        if: ${{ success() }}
        shell: powershell
        run: |
          Write-Host "Copying project files..."
          xcopy . "E:\react" /E /H /C /I /Y /V
          Write-Host "Content after copy:"
          dir "E:\react" -Recurse

      - name: Run PM2 restart via pm1.bat (verbose)
        if: ${{ success() }}
        shell: cmd
        run: |
          echo Running pm1.bat...
          E:\react\pm1.bat 2>&1
          if errorlevel 1 (
            echo ::error::PM2 restart failed with exit code %errorlevel%
            exit /b %errorlevel%
          )
