name: Next.js Full Release Deploy to E:\react

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
      # 1- گرفتن سورس کد
      - name: Checkout code
        uses: actions/checkout@v4

      # 2- تنظیم Node.js نسخه 20 با کش npm
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # 3- نصب وابستگی‌ها
      - name: Install dependencies
        run: npm ci

      # 4- بیلد پروژه
      - name: Build project
        run: npm run build

      # 5- کپی کل پروژه به E:\react (Overwrite کامل)
      - name: Copy full project
        if: ${{ success() }}
        shell: powershell
        run: |
          Write-Host "شروع کپی کامل پروژه..."
          xcopy . "E:\react" /E /H /C /I /Y /V
          Write-Host "محتوای پوشه E:\react بعد از کپی:"
          dir "E:\react" -Recurse

      # 6- فراخوانی فایل pm1.bat برای Kill + Start PM2
      - name: Run PM2 restart from pm1.bat
        if: ${{ success() }}
        shell: cmd
        run: |
          E:\react\pm1.bat
