name: Next.js Full Release Deploy to E:\react

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
      # 1- گرفتن سورس کد
      - name: Checkout code
        uses: actions/checkout@v4

      # 2- تنظیم Node.js نسخه 20 با کش npm
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # 3- نصب وابستگی‌ها
      - name: Install dependencies
        run: npm ci

      # 4- بیلد پروژه
      - name: Build project
        run: npm run build

      # 5- کپی کل پروژه (Full Release) با overwrite
      - name: Copy full project to E:\react
        if: ${{ success() }}
        shell: powershell
        run: |
          Write-Host "شروع کپی کامل پروژه (Full Release)..."
          xcopy . "E:\react" /E /H /C /I /Y /V
          Write-Host "نمایش فایل‌های موجود بعد از کپی:"
          dir "E:\react" -Recurse

      # 6- رفتن به مسیر پروژه و اجرای PM2 از مسیر کامل
      - name: Restart PM2 from project directory
        if: ${{ success() }}
        shell: powershell
        run: |
          # تغییر مسیر به پوشه پروژه
          Set-Location "E:\react"

          # مسیر کامل PM2 برای ویندوز (Global npm bin)
          $pm2Path = "$env:USERPROFILE\AppData\Roaming\npm\pm2.cmd"

          if (-Not (Test-Path $pm2Path)) {
            Write-Host "مسیر PM2 پیدا نشد، لطفاً مسیر نصب Global pm2 را بررسی کنید."
            exit 1
          }

          # ریستارت سرویس api در PM2
          & $pm2Path restart api

          Write-Host "PM2 سرویس api را ریستارت کرد."
