name: Next.js Full Release Deploy to E:\react

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted
    env:
      ACTIONS_STEP_DEBUG: true
      CI: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        shell: cmd
        run: |
          echo Installing dependencies...
          npm ci 2>&1
          if errorlevel 1 (
            echo ::error::Install failed with exit code %errorlevel%
            exit /b %errorlevel%
          )

      - name: Build project (verbose)
        shell: cmd
        run: |
          echo Starting build...
          npm run build 2>&1
          if errorlevel 1 (
            echo ::error::Build failed with exit code %errorlevel%
            exit /b %errorlevel%
          )

      - name: Copy project to E:\react without deleting existing files
        if: ${{ success() }}
        shell: cmd
        run: |
          echo Copying project files to E:\react without removing existing ones ...
          if not exist "E:\react" mkdir "E:\react"

          robocopy . "E:\react" /E /COPYALL /R:3 /W:5 ^
            /XD ".git" ".github" "tests" "docs" ".next/cache" ^
            /XF "*.md" "*.txt" "*.log" ".env.local" "README*" "LICENSE*" ^
            /NFL /NDL /NP /LOG+:deploy.log

          set RC=%ERRORLEVEL%
          if %RC% EQU 16 (
            echo ::error::Robocopy fatal error (exit code 16 - no files copied)
            exit /b %RC%
          )
          if %RC% EQU 11 (
            echo Robocopy completed with exit code 11 (treated as success)
            exit /b 0
          )
          if %RC% GEQ 8 (
            echo ::error::File copy failed with exit code %RC%
            exit /b %RC%
          )
          echo Robocopy completed with exit code %RC% (treated as success)
          dir "E:\react" /S

      - name: Start API via PM2
        shell: cmd
        run: |
          cd /d E:\react
          "%USERPROFILE%\AppData\Roaming\npm\pm2.cmd" stop api
          "%USERPROFILE%\AppData\Roaming\npm\pm2.cmd" delete api
          "%USERPROFILE%\AppData\Roaming\npm\pm2.cmd" start server.js --name api
          "%USERPROFILE%\AppData\Roaming\npm\pm2.cmd" save
          "%USERPROFILE%\AppData\Roaming\npm\pm2.cmd" list
