name: Next.js Build & Deploy to E:\react

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
      # 1- چک‌اوت سورس کد
      - name: Checkout code
        uses: actions/checkout@v4

      # 2- تنظیم Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # 3- نصب کتابخانه‌ها
      - name: Install dependencies
        run: npm ci

      # 4- بیلد پروژه Next.js
      - name: Build project
        run: npm run build

      # 5- کپی فایل‌ها فقط اگر بیلد موفق بود (Overwrite)
      - name: Copy build output to E:\react
        if: ${{ success() }}
        shell: cmd
        run: |
          echo شروع کپی (Overwrite) فایل‌ها...
          xcopy .next E:\react\.next /E /H /C /I /Y /V
          xcopy package.json E:\react /H /C /I /Y /V
          xcopy package-lock.json E:\react /H /C /I /Y /V
          xcopy public E:\react\public /E /H /C /I /Y /V

          echo نمایش فایل‌های موجود بعد از کپی:
          dir E:\react /s

      # 6- ریستارت سرویس PM2
      - name: Restart PM2
        if: ${{ success() }}
        shell: cmd
        run: pm2 restart api
