name: Next.js Build & Deploy to E:\react

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
      # چک‌اوت سورس کد
      - name: Checkout code
        uses: actions/checkout@v4

      # نصب Node.js نسخه 20
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # نصب کتابخانه‌ها
      - name: Install dependencies
        run: npm ci

      # بیلد پروژه
      - name: Build project
        run: npm run build

      # پاکسازی مسیر قدیمی و کپی خروجی ضروری با لاگ
      - name: Deploy build to E:\react
        shell: cmd
        run: |
          echo پاکسازی مسیر قدیمی E:\react...
          rmdir /S /Q E:\react

          echo ایجاد مسیر جدید...
          mkdir E:\react

          echo شروع کپی فایل‌های ضروری...
          xcopy .next E:\react\.next /E /H /C /I /Y /V
          xcopy package.json E:\react /H /C /I /Y /V
          xcopy package-lock.json E:\react /H /C /I /Y /V
          xcopy public E:\react\public /E /H /C /I /Y /V

          echo لیست فایل‌های کپی شده:
          dir E:\react /s

      # ریستارت PM2 بعد از دیپلوی
      - name: Restart PM2
        shell: cmd
        run: pm2 restart my-server
