name: Next.js Full Release Deploy to E:\react

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted
    env:
      ACTIONS_STEP_DEBUG: true
      CI: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        shell: cmd
        run: |
          echo Installing dependencies...
          npm ci 2>&1
          if errorlevel 1 (
            echo ::error::Install failed with exit code %errorlevel%
            exit /b %errorlevel%
          )

      - name: Build project (verbose)
        shell: cmd
        run: |
          echo Starting build...
          npm run build 2>&1
          if errorlevel 1 (
            echo ::error::Build failed with exit code %errorlevel%
            exit /b %errorlevel%
          )

      - name: Stop PM2 and Node processes before copy
        shell: cmd
        run: |
          echo Stopping PM2 services...
          "%USERPROFILE%\AppData\Roaming\npm\pm2.cmd" stop all
          "%USERPROFILE%\AppData\Roaming\npm\pm2.cmd" delete all
          echo Killing any Node.js processes...
          taskkill /F /IM node.exe || echo No Node process found.

      - name: Copy project to E:\react (No ACL copy, full log)
        shell: cmd
        run: |
          echo Copying project files...
          if not exist "E:\react" mkdir "E:\react"

          robocopy . "E:\react" /E /COPY:DAT /R:3 /W:5 ^
            /XD ".git" ".github" "tests" "docs" ".next/cache" ^
            /XF "*.md" "*.txt" "*.log" ".env.local" "README*" "LICENSE*" ^
            /NFL /NDL /NP /TEE /V /LOG+:"E:\actions-runner\_work\entekhab-store\entekhab-store\deploy.log" ^
            || exit /b 0

          echo Directory after copy:
          dir "E:\react" /S

      - name: Start API via PM2
        shell: cmd
        run: |
          cd /d E:\react
          "%USERPROFILE%\AppData\Roaming\npm\pm2.cmd" start server.js --name api
          "%USERPROFILE%\AppData\Roaming\npm\pm2.cmd" save
          "%USERPROFILE%\AppData\Roaming\npm\pm2.cmd" list
