name: Next.js Full Release Deploy to E:\react

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted
    env:
      ACTIONS_STEP_DEBUG: true
      CI: true

    steps:
      - name: Checkout codes
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        shell: cmd
        run: |
          echo Installing dependencies...
          npm ci 2>&1
          if errorlevel 1 (
            echo ::error::Install failed with exit code %errorlevel%
            exit /b %errorlevel%
          )

      - name: Build project (verbose)
        shell: cmd
        run: |
          echo Starting build...
          npm run build 2>&1
          if errorlevel 1 (
            echo ::error::Build failed with exit code %errorlevel%
            exit /b %errorlevel%
          )

      - name: Copy full project to E:\react
        if: ${{ success() }}
        shell: cmd
        run: |
          echo Copying project files to E:\react ...
          robocopy . "E:\react" /MIR /COPYALL /R:3 /W:5 /NFL /NDL /NP /LOG+:deploy.log
          if errorlevel 8 (
            echo ::error::File copy failed with exit code %errorlevel%
            exit /b %errorlevel%
          )
          dir "E:\react" /S

      - name: Start API via PM2
        shell: cmd
        run: |
          cd /d E:\react
          "%USERPROFILE%\AppData\Roaming\npm\pm2.cmd" stop api
          "%USERPROFILE%\AppData\Roaming\npm\pm2.cmd" delete api
          "%USERPROFILE%\AppData\Roaming\npm\pm2.cmd" start server.js --name api
          "%USERPROFILE%\AppData\Roaming\npm\pm2.cmd" save
          "%USERPROFILE%\AppData\Roaming\npm\pm2.cmd" list

      - name: Show last 50 log lines for API
        if: ${{ success() }}
        shell: cmd
        run: |
          "%USERPROFILE%\AppData\Roaming\npm\pm2.cmd" logs api --lines 50
