name: Production_Release

on:
  workflow_dispatch:
    inputs:
      confirm_release:
        description: 'تأیید انتشار به E:\store ؟'
        required: true
        default: 'yes'

jobs:
  release-copy:
    runs-on: self-hosted
    env:
      ACTIONS_STEP_DEBUG: true
      CI: true

    steps:
      - name: Stop PM2 test_server before copy
        shell: cmd
        run: |
          echo Stopping PM2 service: test_server ...
          "%USERPROFILE%\AppData\Roaming\npm\pm2.cmd"  stop test_server || echo Service not running, continuing...
                    "%USERPROFILE%\AppData\Roaming\npm\pm2.cmd"  stop Production_server || echo Service not running, continuing...

          "%USERPROFILE%\AppData\Roaming\npm\pm2.cmd" list

      - name: Copy updated files from E:\react to E:\store (overwrite only same names)
        shell: cmd
        run: |
          echo Starting selective overwrite from E:\react to E:\store ...
          if not exist "E:\store" mkdir "E:\store"

          robocopy "E:\react" "E:\store" /E /COPY:DAT /R:3 /W:5 ^
            /NFL /NDL /NP /TEE /V ^
            /XF "web.config" "server.js" ^
            /LOG+:"E:\actions-runner\_work\release-copy.log" ^
            || exit /b 0

          echo ✅ Release copy completed. Files with same name were overwritten, others untouched.
          echo ❌ web.config و server.js عمداً کپی نشدند.

      - name: Restart PM2 test_server Production_server after copy
        shell: cmd
        run: |
          echo Restarting PM2 service: test_server ...
          "%USERPROFILE%\AppData\Roaming\npm\pm2.cmd"  restart test_server || echo PM2 start failed, continuing...
          "%USERPROFILE%\AppData\Roaming\npm\pm2.cmd"  restart Production_server || echo PM2 start failed, continuing...

          "%USERPROFILE%\AppData\Roaming\npm\pm2.cmd" save
          "%USERPROFILE%\AppData\Roaming\npm\pm2.cmd" list
