name: Production_server

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Check Node.js version
        shell: cmd
        run: |
          node -v

      - name: Copy files from E:\react to E:\store (exclude node_modules, web.config, server.js)
        shell: cmd
        run: |
          echo Copying files...
          robocopy "E:\react" "E:\store" /E /XO /COPY:DAT ^
            /XD node_modules ^
            /XF web.config server.js ^
            || exit /b 0

      - name: Install npm packages in E:\store
        shell: cmd
        run: |
          cd /d E:\store
          echo Installing npm packages...
          npm install

      - name: Restart PM2 NextServer
        shell: cmd
        run: |
          echo Restarting PM2 service: store_server ...
          "%USERPROFILE%\AppData\Roaming\npm\pm2.cmd" restart NextServer || exit /b 0
          "%USERPROFILE%\AppData\Roaming\npm\pm2.cmd" save
          "%USERPROFILE%\AppData\Roaming\npm\pm2.cmd" list
