name: Production_server

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Check Node.js version
        shell: cmd
        run: |
          node -v

      - name: Copy files from E:\react to E:\store (exclude node_modules, web.config, server.js)
        shell: cmd
        run: |
          echo Copying files...
          robocopy "E:\react" "E:\store" /E /XO /COPY:DAT ^
            /XD node_modules ^
            /XF web.config server.js ^
            || exit /b 0

      - name: Run npm install in E:\store
        shell: cmd
        run: |
          cd /d E:\store
          echo Installing npm packages...
          "%USERPROFILE%\AppData\Roaming\npm\pm2.cmd" restart NextServer || echo PM2 restart failed, continuing...
          "%USERPROFILE%\AppData\Roaming\npm\pm2.cmd" save
          "%USERPROFILE%\AppData\Roaming\npm\pm2.cmd" list

      - name: Restart PM2 store_server
        shell: cmd
        run: |
          echo Restarting PM2 service...
          pm2 restart NextServer || exit /b 0
