name: Production_Release

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, windows]

    steps:
      - name: Stop PM2 service and kill Node.js processes
        shell: cmd
        run: |
          echo Stopping PM2 services...
          "%USERPROFILE%\AppData\Roaming\npm\pm2.cmd" stop all || echo PM2 stop failed or no process running.
          
          echo Killing all node.exe processes...
          tasklist | find /I "node.exe"
          taskkill /F /IM node.exe || echo No Node.js process found.
          timeout /T 2 > nul

      - name: Copy build files from E:\react to E:\store (overwrite only, no deletion)
        shell: cmd
        run: |
          echo Copying files...
          robocopy "E:\react" "E:\store" /E /XO /COPY:DAT /R:3 /W:5 /XF server.js web.config /XD .git .github .next\cache docs tests || exit /b 0
          echo Copy completed.

      - name: Start PM2 service after success
        if: success()
        shell: cmd
        run: |
          echo Starting PM2 services (success case)...
          "%USERPROFILE%\AppData\Roaming\npm\pm2.cmd" start "E:\store\server.js" --name test_server || echo PM2 start failed.
          "%USERPROFILE%\AppData\Roaming\npm\pm2.cmd" save
          "%USERPROFILE%\AppData\Roaming\npm\pm2.cmd" list

      - name: Start PM2 service if workflow failed
        if: failure()
        shell: cmd
        run: |
          echo WARNING: Workflow failed! Restarting PM2 to keep service alive...
          "%USERPROFILE%\AppData\Roaming\npm\pm2.cmd" start "E:\store\server.js" --name test_server || echo PM2 start failed.
          "%USERPROFILE%\AppData\Roaming\npm\pm2.cmd" save
          "%USERPROFILE%\AppData\Roaming\npm\pm2.cmd" list

